#lang racket/base
;; Generated by: ruyi init
;; Language: racket
(require racket/runtime-path)
(require (file "/Users/lizc/.ruyi/config.rkt"))
(provide local-config local-mode-name)

(define-runtime-path here ".")
(define local-mode-name "freestyle")

(define local-config
  (repo-config
   "ruyi"  ; name
   here  ; path (resolved at runtime)
   "main"  ; base-branch
   '(".")  ; source-dirs
   '(".rkt")  ; source-exts
   '("compiled/")  ; excluded-dirs
   'sibling  ; test-pattern
   #f  ; test-dir
   '()  ; forbidden-files
   '(("raco" "make" "claude.rkt" "config.rkt" "detect.rkt" "engine.rkt" "evolve.rkt" "git.rkt" "init.rkt" "judge.rkt" "log.rkt" "tasks.rkt" "validate.rkt") ("raco" "test" "."))  ; validate-commands
   '()  ; priority-dirs
   '()  ; context-files
   "evolution-log.tsv"  ; log-path
   20  ; max-iterations
   3   ; max-consecutive-fails
   500))  ; max-diff-lines
