#lang racket/base
(require racket/string racket/format racket/path racket/file racket/port racket/system
         racket/runtime-path)
(require "config.rkt" "detect.rkt" "claude.rkt")
(provide ruyi-init! ruyi-ensure-init!)

;; Directory where ruyi is installed (this file's directory)
(define-runtime-path ruyi-dir ".")

(define RUYI-CONFIG-FILE ".ruyi.rkt")

;; ============================================================
;; init: detect project + generate .ruyi.rkt (no intent needed)
;; ============================================================

(define (ruyi-init! path)
  "Detect project and generate .ruyi.rkt config."

  (printf "\n=== Ruyi Init ===\n\n")

  ;; Detect project
  (define info (detect-project path))
  (printf "Detected: ~a\n" (describe-project info))
  (printf "Path:     ~a\n\n" (path->string path))

  (when (string=? (project-info-language info) "unknown")
    (printf "No project type detected — running without build/test validation.\n"))

  ;; Ensure git
  (unless (directory-exists? (build-path path ".git"))
    (printf "No git repo found. Initializing...\n")
    (parameterize ([current-directory path])
      (system "git init")
      ;; Create initial commit (even if empty, use --allow-empty)
      (system "git add -A")
      (system "git commit --allow-empty -m 'initial commit'")))

  ;; Detect base branch (default "main" if no commits yet)
  (define base-branch
    (let ([raw (string-trim
                (with-output-to-string
                  (lambda ()
                    (parameterize ([current-directory path])
                      (system "git rev-parse --abbrev-ref HEAD 2>/dev/null || echo main")))))])
      (if (string=? raw "") "main" raw)))

  ;; Generate config
  (define config-content
    (generate-config path info base-branch))

  (define config-path (build-path path RUYI-CONFIG-FILE))
  (call-with-output-file config-path
    (lambda (out) (display config-content out))
    #:exists 'replace)

  (printf "Created: ~a\n" RUYI-CONFIG-FILE)
  (printf "Ready!\n\n"))

;; ============================================================
;; ensure-init: auto-init if .ruyi.rkt doesn't exist
;; ============================================================

(define (ruyi-ensure-init! path)
  "If .ruyi.rkt doesn't exist, run init automatically."
  (define config-path (build-path path RUYI-CONFIG-FILE))
  (unless (file-exists? config-path)
    (ruyi-init! path)))

;; ============================================================
;; Config file generator
;; ============================================================

(define (generate-config path info base-branch)
  (define lang (project-info-language info))
  (define source-dirs (project-info-source-dirs info))
  (define source-exts (project-info-source-exts info))
  (define excluded (project-info-excluded-dirs info))
  (define test-pat (project-info-test-pattern info))
  (define test-dir (project-info-test-dir info))
  (define forbidden (project-info-forbidden-files info))
  (define build-cmds (project-info-build-commands info))
  (define test-cmds (project-info-test-commands info))

  (string-append
   "#lang racket/base\n"
   ";; Generated by: ruyi init\n"
   ";; Language: " lang "\n"
   "(require racket/runtime-path)\n"
   "(require (file \""
   (path->string (simplify-path (build-path (expand-user-path "~/.ruyi") "config.rkt")))
   "\"))\n"
   "(provide local-config local-mode-name)\n\n"
   "(define-runtime-path here \".\")\n"
   "(define local-mode-name \"freestyle\")\n\n"
   "(define local-config\n"
   "  (repo-config\n"
   "   \"" (let-values ([(base name must-be-dir?) (split-path path)])
             (path->string name)) "\"  ; name\n"
   "   here  ; path (resolved at runtime)\n"
   "   \"" base-branch "\"  ; base-branch\n"
   "   '" (format "~s" source-dirs) "  ; source-dirs\n"
   "   '" (format "~s" source-exts) "  ; source-exts\n"
   "   '" (format "~s" excluded) "  ; excluded-dirs\n"
   "   '" (symbol->string test-pat) "  ; test-pattern\n"
   "   " (if test-dir (format "\"~a\"" test-dir) "#f") "  ; test-dir\n"
   "   '" (format "~s" forbidden) "  ; forbidden-files\n"
   "   '" (format "~s" (append build-cmds test-cmds)) "  ; validate-commands\n"
   "   '()  ; priority-dirs\n"
   "   '()  ; context-files\n"
   "   \"evolution-log.tsv\"  ; log-path\n"
   "   20  ; max-iterations\n"
   "   3   ; max-consecutive-fails\n"
   "   500))  ; max-diff-lines\n"))
