#lang racket/base
(require racket/file racket/string racket/format racket/port racket/list)
(provide (all-defined-out))

;; ============================================================
;; .ruyi-task: the contract between planning and execution
;;
;; Generated by Claude Code (full agent mode), read by ruyi engine.
;; Human-readable, editable, git-trackable.
;; ============================================================

(struct ruyi-task
  (goal           ; string
   validate?      ; boolean: run build/test?
   max-revisions  ; integer: review-revise rounds per subtask
   min-score      ; integer: reviewer threshold
   max-diff       ; integer: max diff lines per subtask
   reviewer-model ; string: "sonnet" | "opus"
   auto-merge?    ; boolean: auto PR merge?
   forbidden      ; (listof string): files not to touch
   context        ; (listof string): reference files
   judgement      ; string: custom review criteria
   subtasks)      ; (listof string): ordered subtask descriptions
  #:transparent)

(define DEFAULT-TASK
  (ruyi-task "" #t 2 8 500 "sonnet" #t '() '() "" '()))

;; ============================================================
;; Read .ruyi-task (S-expression format)
;; ============================================================

(define (read-ruyi-task path)
  "Read a .ruyi-task file. Returns a ruyi-task struct."
  (define content (file->string path))
  (define expr (with-input-from-string content read))
  (parse-ruyi-task-expr expr))

(define (parse-ruyi-task-expr expr)
  "Parse (ruyi-task (field value) ...) into struct."
  (unless (and (pair? expr) (eq? (car expr) 'ruyi-task))
    (error 'parse-ruyi-task "Expected (ruyi-task ...), got: ~a" expr))
  (define fields (cdr expr))
  (define (get key [default #f])
    (define pair (assq key fields))
    (if pair (cadr pair) default))
  (define (get-list key)
    (define pair (assq key fields))
    (if pair
        (let ([val (cadr pair)])
          (if (list? val) val (list val)))
        '()))

  (ruyi-task
   (or (get 'goal) "")
   (let ([v (get 'validate)]) (if (eq? v #f) #t v))  ; default #t
   (or (get 'max-revisions) 2)
   (or (get 'min-score) 8)
   (or (get 'max-diff) 500)
   (or (get 'reviewer-model) "sonnet")
   (let ([v (get 'auto-merge)]) (if (eq? v #f) #t v))  ; default #t
   (get-list 'forbidden)
   (get-list 'context)
   (or (get 'judgement) "")
   (get-list 'subtasks)))

;; ============================================================
;; Write .ruyi-task
;; ============================================================

(define (write-ruyi-task path task)
  "Write a ruyi-task struct to file as S-expression."
  (call-with-output-file path
    (lambda (out)
      (fprintf out ";; .ruyi-task — generated by Claude Code, executed by ruyi\n")
      (fprintf out ";; Edit freely. Re-run with: ruyi do\n\n")
      (fprintf out "(ruyi-task\n")
      (fprintf out "  (goal ~s)\n" (ruyi-task-goal task))
      (fprintf out "  (validate ~a)\n" (if (ruyi-task-validate? task) "#t" "#f"))
      (fprintf out "  (max-revisions ~a)\n" (ruyi-task-max-revisions task))
      (fprintf out "  (min-score ~a)\n" (ruyi-task-min-score task))
      (fprintf out "  (max-diff ~a)\n" (ruyi-task-max-diff task))
      (fprintf out "  (reviewer-model ~s)\n" (ruyi-task-reviewer-model task))
      (fprintf out "  (auto-merge ~a)\n" (if (ruyi-task-auto-merge? task) "#t" "#f"))
      (fprintf out "  (forbidden ~s)\n" (ruyi-task-forbidden task))
      (fprintf out "  (context ~s)\n" (ruyi-task-context task))
      (fprintf out "  (judgement ~s)\n" (ruyi-task-judgement task))
      (fprintf out "  (subtasks ~s))\n" (ruyi-task-subtasks task)))
    #:exists 'replace))

;; ============================================================
;; Display .ruyi-task summary
;; ============================================================

(define (print-ruyi-task task)
  "Print a human-readable summary of the task."
  (printf "\nGoal: ~a\n" (ruyi-task-goal task))
  (printf "Validate: ~a | Revisions: ~a | Min score: ~a | Max diff: ~a\n"
          (if (ruyi-task-validate? task) "yes" "no")
          (ruyi-task-max-revisions task)
          (ruyi-task-min-score task)
          (ruyi-task-max-diff task))
  (printf "Reviewer: ~a | Auto-merge: ~a\n"
          (ruyi-task-reviewer-model task)
          (if (ruyi-task-auto-merge? task) "yes" "no"))
  (when (not (string=? (ruyi-task-judgement task) ""))
    (printf "Judgement: ~a\n" (ruyi-task-judgement task)))
  (when (not (null? (ruyi-task-forbidden task)))
    (printf "Forbidden: ~a\n" (string-join (ruyi-task-forbidden task) ", ")))
  (when (not (null? (ruyi-task-context task)))
    (printf "Context: ~a\n" (string-join (ruyi-task-context task) ", ")))
  (printf "Subtasks: ~a\n\n" (length (ruyi-task-subtasks task)))
  (for ([st (in-list (ruyi-task-subtasks task))] [i (in-naturals 1)])
    (printf "  ~a. ~a\n" i st))
  (printf "\n"))

;; ============================================================
;; Prompt for Claude Code to generate .ruyi-task
;; ============================================================

(define (task-generation-prompt goal)
  "Build prompt for Claude Code to generate .ruyi-task file."
  (string-append
   "Read the codebase and understand the project.\n\n"
   "The user wants: " goal "\n\n"
   "Generate a .ruyi-task file in the project root with this exact S-expression format:\n\n"
   "```\n"
   "(ruyi-task\n"
   "  (goal \"one sentence summary\")\n"
   "  (validate #t or #f)           ;; run build/test? #t for code, #f for docs\n"
   "  (max-revisions 2)             ;; review-revise rounds per subtask, 1-5\n"
   "  (min-score 8)                 ;; minimum reviewer score to approve, 1-10\n"
   "  (max-diff 500)                ;; max diff lines per subtask\n"
   "  (reviewer-model \"sonnet\")     ;; which model reviews\n"
   "  (auto-merge #t)               ;; auto-merge PR when done\n"
   "  (forbidden (\"file1\" \"file2\")) ;; files not to modify, or ()\n"
   "  (context (\"file1\" \"file2\"))   ;; reference files for implementer, or ()\n"
   "  (judgement \"review criteria\")  ;; custom criteria for reviewer\n"
   "  (subtasks\n"
   "    (\"first subtask description\")\n"
   "    (\"second subtask description\")\n"
   "    (\"third subtask description\")))\n"
   "```\n\n"
   "Rules:\n"
   "- Read the project first to understand structure and conventions\n"
   "- Break the goal into 3-7 small, independent subtasks\n"
   "- Order subtasks by dependency\n"
   "- Each subtask should be completable in one commit\n"
   "- Respect the user's explicit constraints in their goal\n"
   "- Write the file to .ruyi-task in the project root\n"
   "- Output ONLY the file, nothing else\n"))
