#lang racket/base
(require racket/file racket/string racket/format racket/port racket/list racket/date racket/path)
(provide (all-defined-out))

;; ============================================================
;; .ruyi-task: the contract between planning and execution
;;
;; Generated by Claude Code (full agent mode), read by ruyi engine.
;; Human-readable, editable, git-trackable.
;; ============================================================

(struct ruyi-task
  (goal           ; string
   validate?      ; boolean: run build/test?
   max-revisions  ; integer: review-revise rounds per subtask
   min-score      ; integer: reviewer threshold
   max-diff       ; integer: max diff lines per subtask
   reviewer-model ; string: "sonnet" | "opus"
   auto-merge?    ; boolean: auto PR merge?
   forbidden      ; (listof string): files not to touch
   context        ; (listof string): reference files
   judgement      ; string: custom review criteria
   subtasks)      ; (listof string): ordered subtask descriptions
  #:transparent)

(define DEFAULT-TASK
  (ruyi-task "" #t 2 8 500 "sonnet" #t '() '() "" '()))

;; ============================================================
;; Read .ruyi-task (S-expression format)
;; ============================================================

(define (read-ruyi-task path)
  "Read a .ruyi-task file. Returns a ruyi-task struct."
  (define content (file->string path))
  (define expr (with-input-from-string content read))
  (parse-ruyi-task-expr expr))

(define (parse-ruyi-task-expr expr)
  "Parse (ruyi-task (field value) ...) into struct."
  (unless (and (pair? expr) (eq? (car expr) 'ruyi-task))
    (error 'parse-ruyi-task "Expected (ruyi-task ...), got: ~a" expr))
  (define fields (cdr expr))
  (define (get key [default #f])
    (define pair (assq key fields))
    (if pair (cadr pair) default))
  (define (get-list key)
    (define pair (assq key fields))
    (if pair
        (let ([val (cadr pair)])
          (if (list? val) val (list val)))
        '()))

  (ruyi-task
   (or (get 'goal) "")
   (let ([v (get 'validate)]) (if (eq? v #f) #t v))  ; default #t
   (or (get 'max-revisions) 2)
   (or (get 'min-score) 8)
   (or (get 'max-diff) 500)
   (or (get 'reviewer-model) "sonnet")
   (let ([v (get 'auto-merge)]) (if (eq? v #f) #t v))  ; default #t
   (get-list 'forbidden)
   (get-list 'context)
   (or (get 'judgement) "")
   (get-list 'subtasks)))

;; ============================================================
;; Write .ruyi-task
;; ============================================================

(define (write-ruyi-task path task)
  "Write a ruyi-task struct to file as S-expression."
  (call-with-output-file path
    (lambda (out)
      (fprintf out ";; .ruyi-task — generated by Claude Code, executed by ruyi\n")
      (fprintf out ";; Edit freely. Re-run with: ruyi do\n\n")
      (fprintf out "(ruyi-task\n")
      (fprintf out "  (goal ~s)\n" (ruyi-task-goal task))
      (fprintf out "  (validate ~a)\n" (if (ruyi-task-validate? task) "#t" "#f"))
      (fprintf out "  (max-revisions ~a)\n" (ruyi-task-max-revisions task))
      (fprintf out "  (min-score ~a)\n" (ruyi-task-min-score task))
      (fprintf out "  (max-diff ~a)\n" (ruyi-task-max-diff task))
      (fprintf out "  (reviewer-model ~s)\n" (ruyi-task-reviewer-model task))
      (fprintf out "  (auto-merge ~a)\n" (if (ruyi-task-auto-merge? task) "#t" "#f"))
      (fprintf out "  (forbidden ~s)\n" (ruyi-task-forbidden task))
      (fprintf out "  (context ~s)\n" (ruyi-task-context task))
      (fprintf out "  (judgement ~s)\n" (ruyi-task-judgement task))
      (fprintf out "  (subtasks ~s))\n" (ruyi-task-subtasks task)))
    #:exists 'replace))

;; ============================================================
;; Display .ruyi-task summary
;; ============================================================

(define (print-ruyi-task task)
  "Print a human-readable summary of the task."
  (printf "\nGoal: ~a\n" (ruyi-task-goal task))
  (printf "Validate: ~a | Revisions: ~a | Min score: ~a | Max diff: ~a\n"
          (if (ruyi-task-validate? task) "yes" "no")
          (ruyi-task-max-revisions task)
          (ruyi-task-min-score task)
          (ruyi-task-max-diff task))
  (printf "Reviewer: ~a | Auto-merge: ~a\n"
          (ruyi-task-reviewer-model task)
          (if (ruyi-task-auto-merge? task) "yes" "no"))
  (when (not (string=? (ruyi-task-judgement task) ""))
    (printf "Judgement: ~a\n" (ruyi-task-judgement task)))
  (when (not (null? (ruyi-task-forbidden task)))
    (printf "Forbidden: ~a\n" (string-join (ruyi-task-forbidden task) ", ")))
  (when (not (null? (ruyi-task-context task)))
    (printf "Context: ~a\n" (string-join (ruyi-task-context task) ", ")))
  (printf "Subtasks: ~a\n\n" (length (ruyi-task-subtasks task)))
  (for ([st (in-list (ruyi-task-subtasks task))] [i (in-naturals 1)])
    (printf "  ~a. ~a\n" i st))
  (printf "\n"))

;; ============================================================
;; Task folder management
;;
;; .ruyi-tasks/
;;   2026-03-27-improve-docs/
;;     task.rkt          ← task definition
;;     log.tsv           ← execution log
;;     journal.md        ← detailed history
;; ============================================================

(define TASKS-DIR ".ruyi-tasks")
(define TASK-FILENAME "task.rkt")

(define (tasks-dir dir)
  (build-path dir TASKS-DIR))

(define (slugify s)
  "Turn a goal string into a short filesystem-safe slug."
  (define clean
    (regexp-replace* #rx"[^a-zA-Z0-9\u4e00-\u9fff]+" (string-downcase s) "-"))
  (define trimmed
    (if (> (string-length clean) 40)
        (substring clean 0 40)
        clean))
  (string-trim trimmed "-"))

(define (create-task-dir dir goal)
  "Create a new task folder under .ruyi-tasks/. Returns the folder path."
  (define date-str
    (parameterize ([date-display-format 'iso-8601])
      (define d (current-date))
      (format "~a-~a-~a"
              (date-year d)
              (~r (date-month d) #:min-width 2 #:pad-string "0")
              (~r (date-day d) #:min-width 2 #:pad-string "0"))))
  (define slug (slugify goal))
  (define folder-name (format "~a-~a" date-str slug))
  (define folder-path (build-path (tasks-dir dir) folder-name))
  (make-directory* folder-path)
  folder-path)

(define (task-file-in-folder folder)
  (build-path folder TASK-FILENAME))

(define (list-task-dirs dir)
  "List all task folders, newest first."
  (define tdir (tasks-dir dir))
  (if (directory-exists? tdir)
      (sort
       (for/list ([d (directory-list tdir #:build? #t)]
                  #:when (directory-exists? d)
                  #:when (file-exists? (task-file-in-folder d)))
         d)
       string>?
       #:key path->string)
      '()))

(define (latest-task-dir dir)
  "Get the most recent task folder, or #f."
  (define dirs (list-task-dirs dir))
  (if (null? dirs) #f (car dirs)))

(define (print-task-list dir)
  "Print all task folders with their goals."
  (define dirs (list-task-dirs dir))
  (cond
    [(null? dirs)
     (printf "No tasks found.\n")]
    [else
     (printf "Tasks:\n")
     (for ([d (in-list dirs)] [i (in-naturals 1)])
       (define task (read-ruyi-task (task-file-in-folder d)))
       (define name (path->string (file-name-from-path d)))
       (printf "  ~a. ~a — ~a (~a subtasks)\n"
               i name (ruyi-task-goal task) (length (ruyi-task-subtasks task))))]))

;; ============================================================
;; Prompt for Claude Code to generate .ruyi-task
;; ============================================================

(define (task-generation-prompt goal task-folder-path)
  "Build prompt for Claude Code to generate task.rkt in the task folder."
  (string-append
   "Read the codebase and understand the project.\n\n"
   "The user wants: " goal "\n\n"
   "Generate a task file at: " (path->string (task-file-in-folder task-folder-path))
   "\n\nUse this exact S-expression format:\n\n"
   "```\n"
   "(ruyi-task\n"
   "  (goal \"one sentence summary\")\n"
   "  (validate #t or #f)           ;; run build/test? #t for code, #f for docs\n"
   "  (max-revisions 2)             ;; review-revise rounds per subtask, 1-5\n"
   "  (min-score 8)                 ;; minimum reviewer score to approve, 1-10\n"
   "  (max-diff 500)                ;; max diff lines per subtask\n"
   "  (reviewer-model \"sonnet\")     ;; which model reviews\n"
   "  (auto-merge #t)               ;; auto-merge PR when done\n"
   "  (forbidden (\"file1\" \"file2\")) ;; files not to modify, or ()\n"
   "  (context (\"file1\" \"file2\"))   ;; reference files for implementer, or ()\n"
   "  (judgement \"review criteria\")  ;; custom criteria for reviewer\n"
   "  (subtasks\n"
   "    (\"first subtask description\")\n"
   "    (\"second subtask description\")\n"
   "    (\"third subtask description\")))\n"
   "```\n\n"
   "Rules:\n"
   "- Read the project first to understand structure and conventions\n"
   "- Break the goal into 3-7 small, independent subtasks\n"
   "- Order subtasks by dependency\n"
   "- Each subtask should be completable in one commit\n"
   "- Respect the user's explicit constraints in their goal\n"
   "- Write the file to the path specified above\n"
   "- Output ONLY the file, nothing else\n"))
