#lang racket/base
(require racket/file racket/string racket/format racket/port racket/list racket/date racket/path)
(provide (all-defined-out))

;; ============================================================
;; .ruyi-task: the contract between planning and execution
;;
;; Generated by Claude Code (full agent mode), read by ruyi engine.
;; Human-readable, editable, git-trackable.
;; ============================================================

(struct ruyi-task
  (goal           ; string
   build          ; (listof string): build commands, or () to skip
   test           ; (listof string): test commands, or () to skip
   max-revisions  ; integer: review-revise rounds per subtask
   min-score      ; integer: reviewer threshold
   max-diff       ; integer: max diff lines per subtask
   reviewer-model ; string: "sonnet" | "opus"
   auto-merge?    ; boolean: auto PR merge?
   track?         ; boolean: commit task file to git?
   forbidden      ; (listof string): files not to touch
   context        ; (listof string): reference files
   judgement      ; string: custom review criteria
   subtasks)      ; (listof string): ordered subtask descriptions
  #:transparent)

(define DEFAULT-TASK
  (ruyi-task "" '() '() 2 8 500 "sonnet" #t #t '() '() "" '()))

;; ============================================================
;; Read .ruyi-task (S-expression format)
;; ============================================================

(define (read-ruyi-task path)
  "Read a .ruyi-task file. Returns a ruyi-task struct."
  (define content (file->string path))
  (define expr (with-input-from-string content read))
  (parse-ruyi-task-expr expr))

(define (parse-ruyi-task-expr expr)
  "Parse (ruyi-task (field value) ...) into struct."
  (unless (and (pair? expr) (eq? (car expr) 'ruyi-task))
    (error 'parse-ruyi-task "Expected (ruyi-task ...), got: ~a" expr))
  (define fields (cdr expr))
  (define MISSING (gensym 'missing))
  (define (get key [default MISSING])
    (define pair (assq key fields))
    (if pair (cadr pair) default))
  (define (get-bool key default)
    "Get a boolean field. Distinguishes missing from explicit #f."
    (define v (get key))
    (if (eq? v MISSING) default v))
  (define (get-list key)
    "Get a list field. Handles both (key (a b c)) and (key (a) (b) (c)) forms."
    (define pair (assq key fields))
    (if pair
        (let ([rest (cdr pair)])
          (cond
            [(null? rest) '()]
            ;; (key ()) — explicit empty list
            [(and (= (length rest) 1) (null? (car rest)))
             '()]
            ;; (key ("a") ("b") ("c")) — multiple sub-elements
            [(and (pair? (car rest))
                  (> (length rest) 1))
             (map (lambda (item)
                    (if (pair? item) (car item) item))
                  rest)]
            ;; (key ("a" "b" "c")) — single list
            [(pair? (car rest))
             (car rest)]
            ;; (key "a") — single value
            [else (list (car rest))]))
        '()))

  (ruyi-task
   (let ([v (get 'goal)]) (if (eq? v MISSING) "" v))
   (get-list 'build)
   (get-list 'test)
   (let ([v (get 'max-revisions)]) (if (eq? v MISSING) 2 v))
   (let ([v (get 'min-score)]) (if (eq? v MISSING) 8 v))
   (let ([v (get 'max-diff)]) (if (eq? v MISSING) 500 v))
   (let ([v (get 'reviewer-model)]) (if (eq? v MISSING) "sonnet" v))
   (get-bool 'auto-merge #t)
   (get-bool 'track #t)
   (get-list 'forbidden)
   (get-list 'context)
   (let ([v (get 'judgement)]) (if (eq? v MISSING) "" v))
   (get-list 'subtasks)))

;; ============================================================
;; Write .ruyi-task
;; ============================================================

(define (write-ruyi-task path task)
  "Write a ruyi-task struct to file as S-expression."
  (call-with-output-file path
    (lambda (out)
      (fprintf out ";; .ruyi-task — generated by Claude Code, executed by ruyi\n")
      (fprintf out ";; Edit freely. Re-run with: ruyi do\n\n")
      (fprintf out "(ruyi-task\n")
      (fprintf out "  (goal ~s)\n" (ruyi-task-goal task))
      (fprintf out "  (build ~s)\n" (ruyi-task-build task))
      (fprintf out "  (test ~s)\n" (ruyi-task-test task))
      (fprintf out "  (max-revisions ~a)\n" (ruyi-task-max-revisions task))
      (fprintf out "  (min-score ~a)\n" (ruyi-task-min-score task))
      (fprintf out "  (max-diff ~a)\n" (ruyi-task-max-diff task))
      (fprintf out "  (reviewer-model ~s)\n" (ruyi-task-reviewer-model task))
      (fprintf out "  (auto-merge ~a)\n" (if (ruyi-task-auto-merge? task) "#t" "#f"))
      (fprintf out "  (track ~a)\n" (if (ruyi-task-track? task) "#t" "#f"))
      (fprintf out "  (forbidden ~s)\n" (ruyi-task-forbidden task))
      (fprintf out "  (context ~s)\n" (ruyi-task-context task))
      (fprintf out "  (judgement ~s)\n" (ruyi-task-judgement task))
      (fprintf out "  (subtasks ~s))\n" (ruyi-task-subtasks task)))
    #:exists 'replace))

;; ============================================================
;; Display .ruyi-task summary
;; ============================================================

(define (print-ruyi-task task)
  "Print a human-readable summary of the task."
  (printf "\nGoal: ~a\n" (ruyi-task-goal task))
  (when (not (null? (ruyi-task-build task)))
    (printf "Build: ~a\n" (string-join (ruyi-task-build task) " && ")))
  (when (not (null? (ruyi-task-test task)))
    (printf "Test: ~a\n" (string-join (ruyi-task-test task) " && ")))
  (printf "Revisions: ~a | Min score: ~a | Max diff: ~a\n"
          (ruyi-task-max-revisions task)
          (ruyi-task-min-score task)
          (ruyi-task-max-diff task))
  (printf "Reviewer: ~a | Auto-merge: ~a\n"
          (ruyi-task-reviewer-model task)
          (if (ruyi-task-auto-merge? task) "yes" "no"))
  (when (not (string=? (ruyi-task-judgement task) ""))
    (printf "Judgement: ~a\n" (ruyi-task-judgement task)))
  (when (not (null? (ruyi-task-forbidden task)))
    (printf "Forbidden: ~a\n" (string-join (ruyi-task-forbidden task) ", ")))
  (when (not (null? (ruyi-task-context task)))
    (printf "Context: ~a\n" (string-join (ruyi-task-context task) ", ")))
  (printf "Subtasks: ~a\n\n" (length (ruyi-task-subtasks task)))
  (for ([st (in-list (ruyi-task-subtasks task))] [i (in-naturals 1)])
    (printf "  ~a. ~a\n" i st))
  (printf "\n"))

;; ============================================================
;; Subtask completion tracking (done.txt)
;; ============================================================

(define DONE-FILENAME "done.txt")

(define (done-file-path folder)
  (build-path folder DONE-FILENAME))

(define (read-done folder)
  "Read completed subtask indices from done.txt. Returns a set of integers."
  (define p (done-file-path folder))
  (if (file-exists? p)
      (for/list ([line (in-list (string-split (file->string p) "\n"))]
                 #:when (not (string=? (string-trim line) "")))
        (or (string->number (string-trim line)) 0))
      '()))

(define (mark-done! folder index)
  "Append a subtask index to done.txt."
  (define p (done-file-path folder))
  (call-with-output-file p
    (lambda (out) (fprintf out "~a\n" index))
    #:exists 'append))

;; ============================================================
;; Task folder management
;;
;; .ruyi-tasks/
;;   2026-03-27-improve-docs/
;;     task.rkt          ← task definition
;;     log.tsv           ← execution log
;;     journal.md        ← detailed history
;; ============================================================

(define TASKS-DIR ".ruyi-tasks")
(define TASK-FILENAME "task.rkt")

(define (tasks-dir dir)
  (build-path dir TASKS-DIR))

(define (slugify s)
  "Turn a goal string into a short filesystem-safe slug."
  (define clean
    (regexp-replace* #rx"[^a-zA-Z0-9\u4e00-\u9fff]+" (string-downcase s) "-"))
  (define trimmed
    (if (> (string-length clean) 40)
        (substring clean 0 40)
        clean))
  (string-trim trimmed "-"))

(define (create-task-dir dir goal)
  "Create a new task folder under .ruyi-tasks/. Returns the folder path."
  (define date-str
    (parameterize ([date-display-format 'iso-8601])
      (define d (current-date))
      (format "~a-~a-~a"
              (date-year d)
              (~r (date-month d) #:min-width 2 #:pad-string "0")
              (~r (date-day d) #:min-width 2 #:pad-string "0"))))
  (define slug (slugify goal))
  (define folder-name (format "~a-~a" date-str slug))
  (define folder-path (build-path (tasks-dir dir) folder-name))
  (make-directory* folder-path)
  folder-path)

(define (task-file-in-folder folder)
  (build-path folder TASK-FILENAME))

(define (list-task-dirs dir)
  "List all task folders, newest first."
  (define tdir (tasks-dir dir))
  (if (directory-exists? tdir)
      (sort
       (for/list ([d (directory-list tdir #:build? #t)]
                  #:when (directory-exists? d)
                  #:when (file-exists? (task-file-in-folder d)))
         d)
       string>?
       #:key path->string)
      '()))

(define (latest-task-dir dir)
  "Get the most recent task folder, or #f."
  (define dirs (list-task-dirs dir))
  (if (null? dirs) #f (car dirs)))

(define (print-task-list dir)
  "Print all task folders with their goals."
  (define dirs (list-task-dirs dir))
  (cond
    [(null? dirs)
     (printf "No tasks found.\n")]
    [else
     (printf "Tasks:\n")
     (for ([d (in-list dirs)] [i (in-naturals 1)])
       (define task (read-ruyi-task (task-file-in-folder d)))
       (define name (path->string (file-name-from-path d)))
       (printf "  ~a. ~a — ~a (~a subtasks)\n"
               i name (ruyi-task-goal task) (length (ruyi-task-subtasks task))))]))

;; ============================================================
;; Prompt for Claude Code to generate .ruyi-task
;; ============================================================

(define (task-generation-prompt goal task-folder-path ruyi-home)
  "Build prompt for Claude Code to generate task.rkt."
  (define format-file (build-path ruyi-home "RUYI-TASK-FORMAT.md"))
  (string-append
   "The user wants: " goal "\n\n"
   "Read the format spec at: " (path->string format-file) "\n"
   "Then read this project's codebase.\n"
   "Generate the task file at: " (path->string (task-file-in-folder task-folder-path)) "\n"))
