;; .ruyi-task — generated by Claude Code, executed by ruyi
;; Edit freely. Re-run with: ruyi do

(ruyi-task
  (goal "添加 tests/test-task-file.rkt 测试，覆盖 read-ruyi-task、write-ruyi-task 往返、slugify、done.txt 读写")
  (build ())
  (test ("raco test tests/test-task-file.rkt"))
  (max-revisions 2)
  (min-score 8)
  (max-diff 300)
  (reviewer-model "sonnet")
  (auto-merge #t)
  (track #t)
  (forbidden ("engine.rkt" "review.rkt" "claude.rkt" "git.rkt" "evolve.rkt"))
  (context ("task-file.rkt" "tests/test-engine.rkt"))
  (judgement "测试应覆盖所有指定功能：解析、往返一致性、slugify 边界情况、done.txt 读写。使用临时文件，不留副作用。")
  (subtasks
    ("在 tests/test-task-file.rkt 中创建测试骨架：require rackunit 和 task-file.rkt，添加 read-ruyi-task 解析测试——构造一个临时 .ruyi-task 文件，验证解析出的 struct 各字段正确，包括默认值处理")
    ("添加 write-ruyi-task 往返测试：构造 ruyi-task struct，写入临时文件，再读回，断言所有字段一致")
    ("添加 slugify 测试：覆盖英文、中文、混合、超长截断、特殊字符等边界情况")
    ("添加 done.txt 读写测试：在临时目录中测试 mark-done! 和 read-done，验证多次追加和读取结果正确")))
