(ruyi-task
  (goal "Write docs/self-testing.md: bilingual story of ruyi testing itself, finding 3 real bugs, and the value of dual-agent review")
  (build ())
  (test ())
  (max-revisions 2)
  (min-score 8)
  (max-diff 300)
  (reviewer-model "sonnet")
  (auto-merge #t)
  (track #t)
  (forbidden ())
  (context ("task-file.rkt" "engine.rkt" "git.rkt" "review.rkt" "tests/test-task-file.rkt"))
  (judgement "Review for: 1) accuracy — bug descriptions must match actual code changes in commits b44ee41, 8178048, 7273980; 2) bilingual quality — both Chinese and English sections should read naturally, not like machine translation; 3) narrative flow — should tell a compelling story, not just list facts; 4) technical depth — include enough code snippets to show the bugs concretely")
  (subtasks
    ("Create docs/self-testing.md with title, bilingual structure, and the Background section explaining why we used ruyi to test itself — a tool that reviews code should be able to improve its own code; include both Chinese (如意测自己，测出了真问题) and English (Ruyi Tests Itself — And Finds Real Bugs) versions")
    ("Write the Process Overview section: describe running ruyi do to add tests to itself, how the dual-agent loop (Agent A implements, Agent B reviews) worked, and how the reviewer caught issues the implementer missed")
    ("Write Bug #1: subtask parsing only returned the first subtask. Describe the discovery (test failed when parsing multiple subtasks), root cause (cadr only takes second element), and fix (handle three distinct S-expression forms). Include before/after code snippets from task-file.rkt")
    ("Write Bug #2: git diff showed 0 lines for new files. Describe the discovery (reviewer saw empty diff for newly created test file), root cause (untracked files invisible to git diff HEAD), and fix (add git add -A before diff in engine.rkt). Include the key code change")
    ("Write Bug #3: explicit #f for auto-merge was treated as #t. Describe the discovery (test set auto-merge #f but parser returned #t), root cause (#f used as both missing-sentinel and valid value), and fix (gensym MISSING sentinel in task-file.rkt). Include before/after code snippets")
    ("Write the Conclusion section: the value of dual-agent review — the reviewer (Agent B) caught issues that the implementer (Agent A) missed or introduced, proving that adversarial review is not just ceremony but catches real bugs. Add a brief reflection on self-referential testing")))
