(ruyi-task
  (goal "Add unit tests for execute-one-iteration in engine.rkt, specifically testing the soft max-diff limit behavior: (1) when diff exceeds max-diff and attempts remain, the loop should revise (revert + retry with feedback about diff being too large), (2) when diff exceeds max-diff and attempts are exhausted, the result should be 'discard. Tests should mock claude-implement, git-revert!, git-diff-line-count, git-check-forbidden-files, shell!, and review-changes to isolate the diff-limit logic. Add tests to tests/test-engine.rkt.")
  (build ())
  (test ("raco test tests/test-engine.rkt"))
  (max-revisions 3)
  (min-score 8)
  (max-diff 500)
  (reviewer-model "sonnet")
  (auto-merge #f)
  (track #t)
  (forbidden ())
  (context ("engine.rkt" "config.rkt" "tests/test-engine.rkt"))
  (judgement "Tests must exercise the two diff-limit branches in execute-one-iteration: (1) revise path when diff > max-diff and attempt < max-revisions, (2) discard path when diff > max-diff and attempts exhausted. Tests should use mocks/stubs for external dependencies (claude-implement, git-*, review-changes) and verify the iteration-result status and detail. All tests must pass with raco test.")
  (subtasks
    ("Export execute-one-iteration and helper functions (inject-feedback, task-param) from engine.rkt so tests can call them directly, or create testable wrappers")
    ("Add mock infrastructure in tests/test-engine.rkt: parameterizable stubs for claude-implement, git-revert!, git-diff-line-count, git-check-forbidden-files, shell!, and review-changes")
    ("Add test: when diff-lines > max-diff and attempt < max-revisions, execute-one-iteration reverts and retries (revise path) — verify it eventually produces a result after the mock returns within-limit diff on retry")
    ("Add test: when diff-lines > max-diff on all attempts (attempt >= max-revisions), execute-one-iteration returns iteration-result with status 'discard and detail mentioning 'Diff too large'")))
