;; .ruyi-task — generated by Claude Code, executed by ruyi
;; Edit freely. Re-run with: ruyi do

(ruyi-task
  (goal "为 task-file.rkt、review.rkt、engine.rkt 三个核心模块添加功能完整性测试")
  (build ())
  (test ("raco test tests/"))
  (max-revisions 2)
  (min-score 8)
  (max-diff 500)
  (reviewer-model "sonnet")
  (auto-merge #f)
  (track #t)
  (forbidden ("engine.rkt" "review.rkt" "task-file.rkt" "claude.rkt" "git.rkt" "config.rkt" "validate.rkt" "evolve.rkt"))
  (context ("task-file.rkt" "review.rkt" "engine.rkt" "config.rkt" "tests/test-engine.rkt" "tests/test-validate.rkt"))
  (judgement "测试必须使用 rackunit。每个测试用例要有清晰的 test-case 名称。mock 外部调用（claude-execute、git 操作等）而非实际调用。覆盖正常路径和边界情况。忽略 fetch-url.test.ts 等无关测试失败。")
  (subtasks
    ("为 task-file.rkt 添加测试 tests/test-task-file.rkt：覆盖 read-ruyi-task 解析完整 S-expression、parse-ruyi-task-expr 处理缺失字段的默认值、write-ruyi-task 写入后再读回的往返一致性（round-trip）、slugify 对中英文和特殊字符的处理、done.txt 的 read-done/mark-done! 读写和空文件边界")
    ("为 review.rkt 添加测试 tests/test-review.rkt：覆盖 parse-score 从标准格式和异常格式提取分数（含大小写不敏感、缺失 SCORE 时返回默认值 5）、parse-issues 和 parse-suggestions 提取 bullet 列表、parse-section 跨 marker 提取和无 end-marker 情况、format-feedback-for-implementer 对空列表和非空列表的格式化输出")
    ("为 engine.rkt 的 revise 循环逻辑添加测试 tests/test-engine-revise.rkt：测试 inject-feedback 注入反馈到 task extra hash、task-param 从 extra 取值和默认值回退、make-task-mode 的 select-task 按序返回 subtask 并跳过 done 的索引。注意：inject-feedback、task-param 是 engine.rkt 内部未导出函数，需要在测试文件中用 (require (only-in \"../engine.rkt\" ...)) 或直接复制逻辑进行测试；如果无法直接 require，则在测试中重新定义等价函数并标注来源")))
