(ruyi-task
  (goal "Create tests/test-soft-max-diff.rkt to test engine.rkt max-diff soft limit: revise loop on excess diff with attempts left, discard when attempts exhausted")
  (build ())
  (test ("raco test tests/test-soft-max-diff.rkt"))
  (max-revisions 3)
  (min-score 8)
  (max-diff 300)
  (reviewer-model "sonnet")
  (auto-merge #f)
  (track #t)
  (forbidden ())
  (context ("engine.rkt" "config.rkt" "tests/test-engine.rkt"))
  (judgement "Tests must mock claude-implement, git-revert!, git-diff-line-count, git-commit!, review-changes, shell!, and other side-effecting functions. No real Claude calls. Verify: 1) diff exceeding max-diff with attempt < max-revs triggers revise-loop (git-revert + retry with feedback); 2) diff exceeding max-diff with attempt >= max-revs returns iteration-result with 'discard status. Tests should exercise execute-one-iteration directly via mocking.")
  (subtasks
    ("Create tests/test-soft-max-diff.rkt with mock infrastructure: define mock versions of claude-implement, git-revert!, git-diff-line-count, git-commit!, review-changes, shell!, git-check-forbidden-files, and other dependencies used by execute-one-iteration. Use Racket parameters or module-level mutable state to control mock return values. Import the necessary structs (task, mode, repo-config, iteration-result) from config.rkt.")
    ("Add test case: when diff exceeds max-diff and attempt < max-revs, execute-one-iteration should call git-revert! and retry with reduced-diff feedback. Mock git-diff-line-count to return over-limit on first call, under-limit on second call. Verify that claude-implement is called twice (once for initial, once for revision) and the final result is 'keep with a commit.")
    ("Add test case: when diff exceeds max-diff on ALL attempts (attempt reaches max-revs), execute-one-iteration should return iteration-result with status 'discard. Mock git-diff-line-count to always return over-limit. Verify git-revert! is called and the result detail mentions diff too large.")
    ("Run raco test tests/test-soft-max-diff.rkt and fix any issues until all tests pass cleanly.")))
